# Use NGINX to serve static files
FROM nginx:stable-alpine

ENV API_BASE="https://api.ajeevi.in"
# Remove default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy your built dist folder to NGINX html directory
COPY dist/ /usr/share/nginx/html

# (Optional) Add custom NGINX config for SPA routing
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# docker build -t pas-web1 .
# docker run -p 3005:80 demo-react-static 
#http://192.168.0.58:9443/  portainer SWM for deploy
# docker buildx build --platform linux/amd64,linux/arm64 --tag ajeevi32189/pas-web1:latest --push .